
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - CHAT_ADMIN_KEY=${CHAT_ADMIN_KEY}
    ports:
      - "8080:8080"
    environment:
      - CHAT_ADMIN_KEY=${CHAT_ADMIN_KEY}
    restart: unless-stopped
